// Generated by Microsoft TypeSpec

import {
  TodoItem,
  TodoFileAttachment,
  TodoUrlAttachment,
} from "./all/todo/index.js";

export interface CreateJsonRequestBody {
  item: TodoItem;

  attachments?: Array<TodoFileAttachment | TodoUrlAttachment>;
}

export interface ListOptions {
  limit?: number;
  offset?: number;
}

export interface CreateJsonOptions {
  attachments?: Array<TodoFileAttachment | TodoUrlAttachment>;
}

export interface ListOptions {
  limit?: number;
  offset?: number;
}

export interface CreateJsonOptions {
  attachments?: Array<TodoFileAttachment | TodoUrlAttachment>;
}
