// Generated by Microsoft TypeSpec

import { TodoAttachmentPage, NotFoundErrorResponse } from "./index.js";

import {
  Standard4XxResponse,
  Standard5XxResponse,
  TodoUrlAttachment,
  TodoFileAttachment,
} from "../index.js";

import { NoContentResponse, NotFoundResponse } from "../../typespec/http.js";

export interface AttachmentsOperations<Context = unknown> {
  list(
    ctx: Context,
    itemId: number,
  ): Promise<
    | TodoAttachmentPage
    | NotFoundErrorResponse
    | Standard4XxResponse
    | Standard5XxResponse
  >;

  createUrlAttachment(
    ctx: Context,
    itemId: number,
    contents: TodoUrlAttachment,
  ): Promise<
    | NoContentResponse
    | NotFoundResponse
    | Standard4XxResponse
    | Standard5XxResponse
  >;

  createFileAttachment(
    ctx: Context,
    itemId: number,
    contents: TodoFileAttachment,
  ): Promise<
    | NoContentResponse
    | NotFoundResponse
    | Standard4XxResponse
    | Standard5XxResponse
  >;
}
