// Generated by Microsoft TypeSpec

import { Pet, Checkup, Toy, Owner } from "../../pet-store.js";

/**
 * Resource create or update operation model.
 */
export interface PetUpdate {
  name?: string;

  tag?: string;

  age?: number;

  ownerId?: bigint;
}

/**
 * Resource create operation model.
 */
export interface PetCreate {
  name: string;

  tag?: string;

  age: number;

  ownerId: bigint;
}

/**
 * Resource create or update operation model.
 */
export interface CheckupUpdate {
  vetName?: string;

  notes?: string;
}

/**
 * Resource create or update operation model.
 */
export interface InsuranceUpdate {
  provider?: string;

  premium?: number;

  deductible?: number;
}

/**
 * Resource create or update operation model.
 */
export interface OwnerUpdate {
  name?: string;

  age?: number;
}

/**
 * Resource create operation model.
 */
export interface OwnerCreate {
  name: string;

  age: number;
}

/**
 * Resource deleted successfully.
 */
export interface ResourceDeletedResponse {}

/**
 * Resource create operation completed successfully.
 */
export interface PetResourceCreatedResponse {
  /**
   * The status code.
   */
  statusCode: 201;

  body: Pet;
}

/**
 * Paged response of Pet items
 */
export interface PetCollectionWithNextLink {
  /**
   * The items on this page
   */
  value: Pet[];

  /**
   * The link to the next page of items
   */
  nextLink?: string;
}

/**
 * Resource create operation completed successfully.
 */
export interface CheckupResourceCreatedResponse {
  /**
   * The status code.
   */
  statusCode: 201;

  body: Checkup;
}

/**
 * Paged response of Checkup items
 */
export interface CheckupCollectionWithNextLink {
  /**
   * The items on this page
   */
  value: Checkup[];

  /**
   * The link to the next page of items
   */
  nextLink?: string;
}

/**
 * Paged response of Toy items
 */
export interface ToyCollectionWithNextLink {
  /**
   * The items on this page
   */
  value: Toy[];

  /**
   * The link to the next page of items
   */
  nextLink?: string;
}

/**
 * Resource create operation completed successfully.
 */
export interface OwnerResourceCreatedResponse {
  /**
   * The status code.
   */
  statusCode: 201;

  body: Owner;
}

/**
 * Paged response of Owner items
 */
export interface OwnerCollectionWithNextLink {
  /**
   * The items on this page
   */
  value: Owner[];

  /**
   * The link to the next page of items
   */
  nextLink?: string;
}
