// Generated by Microsoft TypeSpec

import { ApiError } from "./index.js";

export interface UserCreatedResponse {
  /**
   * An autogenerated unique id for the user
   */
  id: number;

  /**
   * The user's username
   */
  username: string;

  /**
   * The user's email address
   */
  email: string;

  /**
   * The user's password, provided when creating a user
   * but is otherwise not visible (and hashed by the backend)
   */
  password: string;

  /**
   * Whether the user is validated. Never visible to the API.
   */
  validated: boolean;

  /**
   * The status code.
   */
  statusCode: 200;

  /**
   * The token to use to construct the validate email address url
   */
  token: string;
}

/**
 * The user already exists
 */
export interface UserExistsResponse extends ApiError {
  /**
   * The status code.
   */
  statusCode: 409;

  code: "user-exists";
}

/**
 * The user is invalid (e.g. forgot to enter email address)
 */
export interface InvalidUserResponse extends ApiError {
  statusCode: 422;

  code: "invalid-user";
}
