// Generated by Microsoft TypeSpec

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export interface NoContentResponse {
  /**
   * The status code.
   */
  statusCode: 204;
}
