// Generated by Microsoft TypeSpec

import * as http from "node:http";

import * as serverRaw from "./operations/server-raw.js";

import { WidgetService } from "../models/all/demo-service.js";

import {
  RouterOptions,
  createPolicyChain,
  createPolicyChainForRoute,
  HttpContext,
} from "../helpers/router.js";

export interface DemoServiceRouter {
  /**
   * Dispatches the request to the appropriate service based on the request path.
   *
   * This member function may be used directly as a handler for a Node HTTP server.
   *
   * @param request - The incoming HTTP request.
   * @param response - The outgoing HTTP response.
   */
  dispatch(request: http.IncomingMessage, response: http.ServerResponse): void;

  /**
   * An Express middleware function that dispatches the request to the appropriate service based on the request path.
   *
   * This member function may be used directly as an application-level middleware function in an Express app.
   *
   * If the router does not match a route, it will call the `next` middleware registered with the application,
   * so it is sensible to insert this middleware at the beginning of the middleware stack.
   *
   * @param req - The incoming HTTP request.
   * @param res - The outgoing HTTP response.
   * @param next - The next middleware function in the stack.
   */
  expressMiddleware(
    req: http.IncomingMessage,
    res: http.ServerResponse,
    next: () => void,
  ): void;
}

export function createDemoServiceRouter(
  widgetService: WidgetService,
  options: RouterOptions<{
    widgetService: WidgetService<HttpContext>;
  }> = {},
): DemoServiceRouter {
  const onRouteNotFound =
    options.onRequestNotFound ??
    ((request, response) => {
      response.statusCode = 404;
      response.setHeader("Content-Type", "text/plain");
      response.end("Not Found");
    });

  const onInvalidRequest =
    options.onInvalidRequest ??
    ((request, response, route, error) => {
      response.statusCode = 400;
      response.setHeader("Content-Type", "application/json");
      response.end(JSON.stringify({ error }));
    });

  const onInternalError =
    options.onInternalError ??
    ((error, request, response) => {
      response.statusCode = 500;
      response.setHeader("Content-Type", "text/plain");
      response.end("Internal server error.");
    });

  const routePolicies = options.routePolicies ?? {};

  const routeHandlers = {
    widget_service_get: createPolicyChainForRoute(
      "widgetServiceGetDispatch",
      routePolicies,
      "widgetService",
      "get",
      serverRaw.widget_service_get,
    ),
    widget_service_update: createPolicyChainForRoute(
      "widgetServiceUpdateDispatch",
      routePolicies,
      "widgetService",
      "update",
      serverRaw.widget_service_update,
    ),
    widget_service_delete: createPolicyChainForRoute(
      "widgetServiceDeleteDispatch",
      routePolicies,
      "widgetService",
      "delete",
      serverRaw.widget_service_delete,
    ),
    widget_service_create: createPolicyChainForRoute(
      "widgetServiceCreateDispatch",
      routePolicies,
      "widgetService",
      "create",
      serverRaw.widget_service_create,
    ),
    widget_service_list: createPolicyChainForRoute(
      "widgetServiceListDispatch",
      routePolicies,
      "widgetService",
      "list",
      serverRaw.widget_service_list,
    ),
  } as const;

  const dispatch = createPolicyChain(
    "DemoServiceRouterDispatch",
    options.policies ?? [],
    async function (ctx, request, response, onRouteNotFound) {
      const url = new URL(request.url!, `http://${request.headers.host}`);
      let path = url.pathname;

      if (path.length === 0) {
        return onRouteNotFound(request, response);
      } else if (path.startsWith("/")) {
        path = path.slice(1);
        if (path.length === 0) {
          switch (request.method) {
            case "POST":
              return routeHandlers.widget_service_create(
                ctx,
                request,
                response,
                widgetService,
              );
            case "GET":
              return routeHandlers.widget_service_list(
                ctx,
                request,
                response,
                widgetService,
              );
            default:
              return onRouteNotFound(request, response);
          }
        } else {
          let __id_idx = path.indexOf("/");
          __id_idx = __id_idx === -1 ? path.length : __id_idx;
          const id = path.slice(0, __id_idx);
          path = path.slice(__id_idx);
          if (path.length === 0) {
            switch (request.method) {
              case "GET":
                return routeHandlers.widget_service_get(
                  ctx,
                  request,
                  response,
                  widgetService,
                  id,
                );
              case "PATCH":
                return routeHandlers.widget_service_update(
                  ctx,
                  request,
                  response,
                  widgetService,
                  id,
                );
              case "DELETE":
                return routeHandlers.widget_service_delete(
                  ctx,
                  request,
                  response,
                  widgetService,
                  id,
                );
              default:
                return onRouteNotFound(request, response);
            }
          } else {
            return onRouteNotFound(request, response);
          }
        }
      }

      return onRouteNotFound(request, response);
    },
  );

  return {
    dispatch(request, response) {
      return dispatch(
        { request, response },
        request,
        response,
        onRouteNotFound,
      ).catch((e) => onInternalError(e, request, response));
    },
    expressMiddleware: function (request, response, next) {
      void dispatch({ request, response }, request, response, function () {
        next();
      }).catch((e) => onInternalError(e, request, response));
    },
  };
}
