// Code generated by Microsoft (R) TypeSpec Code Generator.

module petstore {
    requires transitive io.clientcore.core;

    exports petstore;
    exports petstore.models;
    exports typespec.rest.resource.models;

    opens petstore.models to io.clientcore.core;
    opens typespec.rest.resource.models to io.clientcore.core;
}
