// Code generated by Microsoft (R) TypeSpec Code Generator.

package petstore;

import io.clientcore.core.annotation.Metadata;
import io.clientcore.core.annotation.ServiceClient;
import io.clientcore.core.http.exception.HttpResponseException;
import io.clientcore.core.http.models.RequestOptions;
import io.clientcore.core.http.models.Response;
import petstore.implementation.ToysImpl;
import petstore.models.Toy;
import typespec.rest.resource.models.ToyCollectionWithNextLink;

/**
 * Initializes a new instance of the synchronous PetStoreClient type.
 */
@ServiceClient(builder = PetStoreClientBuilder.class)
public final class ToysClient {
    @Metadata(generated = true)
    private final ToysImpl serviceClient;

    /**
     * Initializes an instance of ToysClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Metadata(generated = true)
    ToysClient(ToysImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * Gets an instance of the resource.
     * 
     * @param petId The petId parameter.
     * @param toyId The toyId parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return an instance of the resource.
     */
    @Metadata(generated = true)
    public Response<Toy> getWithResponse(int petId, long toyId, RequestOptions requestOptions) {
        return this.serviceClient.getWithResponse(petId, toyId, requestOptions);
    }

    /**
     * The list operation.
     * 
     * @param petId The petId parameter.
     * @param nameFilter The nameFilter parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return paged response of Toy items.
     */
    @Metadata(generated = true)
    public Response<ToyCollectionWithNextLink> listWithResponse(int petId, String nameFilter,
        RequestOptions requestOptions) {
        return this.serviceClient.listWithResponse(petId, nameFilter, requestOptions);
    }

    /**
     * Gets an instance of the resource.
     * 
     * @param petId The petId parameter.
     * @param toyId The toyId parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return an instance of the resource.
     */
    @Metadata(generated = true)
    public Toy get(int petId, long toyId) {
        // Generated convenience method for getWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return getWithResponse(petId, toyId, requestOptions).getValue();
    }

    /**
     * The list operation.
     * 
     * @param petId The petId parameter.
     * @param nameFilter The nameFilter parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return paged response of Toy items.
     */
    @Metadata(generated = true)
    public ToyCollectionWithNextLink list(int petId, String nameFilter) {
        // Generated convenience method for listWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return listWithResponse(petId, nameFilter, requestOptions).getValue();
    }
}
