// Generated by Microsoft TypeSpec

import * as http from "node:http";

import { HttpContext } from "../../helpers/router.js";

import {
  Users,
  User,
  TodoItems,
  TodoFileAttachment,
  TodoUrlAttachment,
} from "../../models/all/todo/index.js";

import {
  TodoPage,
  TodoItemPatch,
  Attachments,
} from "../../models/all/todo/todo-items.js";

import { CreateRequestBody } from "../../models/synthetic.js";

export async function users_create(
  ctx: HttpContext,
  request: http.IncomingMessage,
  response: http.ServerResponse,
  operations: Users,
): Promise<void> {
  if (!request.headers["content-type"]?.startsWith("application/json")) {
    throw new Error(
      `Invalid Request: expected content-type 'application/json' but got '${request.headers["content-type"]?.split(";", 2)[0]}'.`,
    );
  }

  const user = (await new Promise(function parseUser(resolve, reject) {
    const chunks: Array<Buffer> = [];
    request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    request.on("end", function finalize() {
      resolve(JSON.parse(Buffer.concat(chunks).toString()));
    });
  })) as User;

  const result = await operations.create(ctx, user);

  if ("statusCode" in result && result.statusCode === 200) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end(JSON.stringify(result));
  } else if ("statusCode" in result && result.statusCode === 409) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end(JSON.stringify(result));
  } else if ("statusCode" in result && result.statusCode === 422) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end(JSON.stringify(result));
  } else if (
    "statusCode" in result &&
    result.statusCode >= 400 &&
    result.statusCode <= 499
  ) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  } else if (
    "statusCode" in result &&
    result.statusCode >= 500 &&
    result.statusCode <= 599
  ) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  }
}

export async function todo_items_list(
  ctx: HttpContext,
  request: http.IncomingMessage,
  response: http.ServerResponse,
  operations: TodoItems,
): Promise<void> {
  const __query_params = new URLSearchParams(
    request.url!.split("?", 1)[1] ?? "",
  );

  const limit = __query_params.get("limit") ?? undefined;
  const offset = __query_params.get("offset") ?? undefined;
  const result = await operations.list(ctx, {
    limit: Number(limit),
    offset: Number(offset),
  });

  if ("items" in result) {
    response.end(JSON.stringify(TodoPage.toJsonObject(result as TodoPage)));
  } else if (
    "statusCode" in result &&
    result.statusCode >= 400 &&
    result.statusCode <= 499
  ) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  } else if (
    "statusCode" in result &&
    result.statusCode >= 500 &&
    result.statusCode <= 599
  ) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  }
}

export async function todo_items_create(
  ctx: HttpContext,
  request: http.IncomingMessage,
  response: http.ServerResponse,
  operations: TodoItems,
): Promise<void> {
  const contentType = request.headers["Content-Type"] as string | undefined;
  if (contentType === undefined) {
    throw new Error("Invalid request: missing required header 'Content-Type'.");
  }

  if (!request.headers["content-type"]?.startsWith("application/json")) {
    throw new Error(
      `Invalid Request: expected content-type 'application/json' but got '${request.headers["content-type"]?.split(";", 2)[0]}'.`,
    );
  }

  const createRequestBody = (await new Promise(function parseCreateRequestBody(
    resolve,
    reject,
  ) {
    const chunks: Array<Buffer> = [];
    request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    request.on("end", function finalize() {
      resolve(JSON.parse(Buffer.concat(chunks).toString()));
    });
  })) as CreateRequestBody;

  const result = await operations.create(ctx, createRequestBody.item, {
    attachments: createRequestBody.attachments,
  });

  if ("id" in result) {
    response.end(JSON.stringify(result));
  } else if ("statusCode" in result && result.statusCode === 422) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  } else if (
    "statusCode" in result &&
    result.statusCode >= 400 &&
    result.statusCode <= 499
  ) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  } else if (
    "statusCode" in result &&
    result.statusCode >= 500 &&
    result.statusCode <= 599
  ) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  }
}

export async function todo_items_get(
  ctx: HttpContext,
  request: http.IncomingMessage,
  response: http.ServerResponse,
  operations: TodoItems,
  id: string,
): Promise<void> {
  const result = await operations.get(ctx, Number(id));

  if ("id" in result) {
    response.end(JSON.stringify(result));
  } else if ("statusCode" in result && result.statusCode === 404) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end(JSON.stringify(result));
  }
}

export async function todo_items_update(
  ctx: HttpContext,
  request: http.IncomingMessage,
  response: http.ServerResponse,
  operations: TodoItems,
  id: string,
): Promise<void> {
  const contentType = request.headers["Content-Type"] as string | undefined;
  if (contentType === undefined) {
    throw new Error("Invalid request: missing required header 'Content-Type'.");
  }

  if (
    !request.headers["content-type"]?.startsWith("application/merge-patch+json")
  ) {
    throw new Error(
      `Invalid Request: expected content-type 'application/merge-patch+json' but got '${request.headers["content-type"]?.split(";", 2)[0]}'.`,
    );
  }

  const patch = (await new Promise(function parsePatch(resolve, reject) {
    const chunks: Array<Buffer> = [];
    request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    request.on("end", function finalize() {
      resolve(JSON.parse(Buffer.concat(chunks).toString()));
    });
  })) as TodoItemPatch;

  const result = await operations.update(ctx, Number(id), patch);

  response.end(JSON.stringify(result));
}

export async function todo_items_delete(
  ctx: HttpContext,
  request: http.IncomingMessage,
  response: http.ServerResponse,
  operations: TodoItems,
  id: string,
): Promise<void> {
  const result = await operations.delete(ctx, Number(id));

  if ("statusCode" in result && result.statusCode === 204) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  } else if ("statusCode" in result && result.statusCode === 404) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end(JSON.stringify(result));
  } else if (
    "statusCode" in result &&
    result.statusCode >= 400 &&
    result.statusCode <= 499
  ) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  } else if (
    "statusCode" in result &&
    result.statusCode >= 500 &&
    result.statusCode <= 599
  ) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  }
}

export async function attachments_list(
  ctx: HttpContext,
  request: http.IncomingMessage,
  response: http.ServerResponse,
  operations: Attachments,
  itemId: string,
): Promise<void> {
  const result = await operations.list(ctx, Number(itemId));

  if ("items" in result) {
    response.end(JSON.stringify(result));
  } else if ("statusCode" in result && result.statusCode === 404) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end(JSON.stringify(result));
  } else if (
    "statusCode" in result &&
    result.statusCode >= 400 &&
    result.statusCode <= 499
  ) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  } else if (
    "statusCode" in result &&
    result.statusCode >= 500 &&
    result.statusCode <= 599
  ) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  }
}

export async function attachments_create_attachment(
  ctx: HttpContext,
  request: http.IncomingMessage,
  response: http.ServerResponse,
  operations: Attachments,
  itemId: string,
): Promise<void> {
  if (!request.headers["content-type"]?.startsWith("application/json")) {
    throw new Error(
      `Invalid Request: expected content-type 'application/json' but got '${request.headers["content-type"]?.split(";", 2)[0]}'.`,
    );
  }

  const contents = (await new Promise(function parseContents(resolve, reject) {
    const chunks: Array<Buffer> = [];
    request.on("data", function appendChunk(chunk) {
      chunks.push(chunk);
    });
    request.on("end", function finalize() {
      resolve(JSON.parse(Buffer.concat(chunks).toString()));
    });
  })) as TodoFileAttachment | TodoUrlAttachment;

  const result = await operations.createAttachment(
    ctx,
    Number(itemId),
    contents,
  );

  if ("statusCode" in result && result.statusCode === 204) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  } else if ("statusCode" in result && result.statusCode === 404) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end(JSON.stringify(result));
  } else if (
    "statusCode" in result &&
    result.statusCode >= 400 &&
    result.statusCode <= 499
  ) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  } else if (
    "statusCode" in result &&
    result.statusCode >= 500 &&
    result.statusCode <= 599
  ) {
    response.statusCode = result.statusCode;
    delete (result as any).statusCode;
    response.end();
  }
}
